### PR TITLE
Add missing DeleteCodedOutputStream function, protobuf-native: release 0.2.2+3.19.1

### PR DESCRIPTION
**Pull request by def-**
As noticed in https://github.com/MaterializeInc/materialize/pull/25177

Also noticed elsewhere: https://github.com/rust-lang/rustc_codegen_cranelift/issues/1411

### CODE REVIEW

**Review by benesch — APPROVED** [review]
Oops, thanks!

**Review by benesch — CHANGES_REQUESTED** [review]
Actually, can you back out the last commit? I'll auto generate that with `cargo release` when I follow the maintainer instructions (https://github.com/MaterializeInc/rust-protobuf-native/blob/master/MAINTAINERS.md). Just leave the bullet point under "[Unreleased]" in the CHANGELOG.md

**Comment by def-** [comment]
Done

**Review by benesch — APPROVED** [review]

**Comment by def-** [comment]
Screenshot 2024-02-14 at 08 51 42
Something went slightly wrong I guess? ;)

**Comment by benesch** [comment]
Lol, no kidding. The release seems to have made it to crates.io successfully at least?

**Pull request merged**
